POST http://localhost:8080/brs/add
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY3YTFjOGQ5NmEwMDI4MzhlOGU0OTUiLCJpYXQiOjE2NTE1NTY0NzksImV4cCI6MTY1MTY0Mjg3OX0.hG9vLZ26SHHXJxoWZcFKI8qQs8tFQiqYPC76WqnAq1Q

{
  "id":"1",
  "rates":1,
  "objs":["626fab651708271ca52a2a58","626f6ae3a713ce25ab142e8c"],
  "descriptions": "Người tham gia được thanh toán 100% chi phí KCB thuộc phạm vi chi trả BHYT và không áp dụng giới hạn tỷ lệ thanh toán một số thuốc, hóa chất, vật tư y tế (VTYT) và dịch vụ kỹ thuật (DVKT) theo quy định của Bộ trưởng Bộ Y tế về danh mục và tỷ lệ, điều kiện thanh toán DVKT; chi phí vận chuyển người bệnh từ tuyến huyện lên tuyến trên trong trường hợp cấp cứu hoặc khi đang điều trị nội trú phải chuyển tuyến chuyên môn kỹ thuật."
}

###
// update
PATCH http://localhost:8080/brs/edit
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY3YTFjOGQ5NmEwMDI4MzhlOGU0OTUiLCJpYXQiOjE2NTE1NTY0NzksImV4cCI6MTY1MTY0Mjg3OX0.hG9vLZ26SHHXJxoWZcFKI8qQs8tFQiqYPC76WqnAq1Q

{
  "_id":"6270c69b860042e9a112138e",
  "id":"1",
  "rates":1,
  "objs":[],
  "descriptions": "Người tham gia được thanh toán 100% chi phí KCB thuộc phạm vi chi trả BHYT và không áp dụng giới hạn tỷ lệ thanh toán một số thuốc, hóa chất, vật tư y tế (VTYT) và dịch vụ kỹ thuật (DVKT) theo quy định của Bộ trưởng Bộ Y tế về danh mục và tỷ lệ, điều kiện thanh toán DVKT; chi phí vận chuyển người bệnh từ tuyến huyện lên tuyến trên trong trường hợp cấp cứu hoặc khi đang điều trị nội trú phải chuyển tuyến chuyên môn kỹ thuật."
}

###
// delete
DELETE  http://localhost:8080/brs/delete?_id=626f6ae3a713ce25ab142e8c
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY3YTFjOGQ5NmEwMDI4MzhlOGU0OTUiLCJpYXQiOjE2NTE0Njc5NTksImV4cCI6MTY1MTU1NDM1OX0.17KXND3Kk1d3AyxHcHh55mopjg80LgL-UFck24qDAOg

###
// get all
GET  http://localhost:8080/brs/getall
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY3YTFjOGQ5NmEwMDI4MzhlOGU0OTUiLCJpYXQiOjE2NTE0Njc5NTksImV4cCI6MTY1MTU1NDM1OX0.17KXND3Kk1d3AyxHcHh55mopjg80LgL-UFck24qDAOg

###
// get by _id
GET  http://localhost:8080/brs/getbyid?_id=626f72c566c55bf68719767f
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY3YTFjOGQ5NmEwMDI4MzhlOGU0OTUiLCJpYXQiOjE2NTE0Njc5NTksImV4cCI6MTY1MTU1NDM1OX0.17KXND3Kk1d3AyxHcHh55mopjg80LgL-UFck24qDAOg