POST http://localhost:8080/mfs/add
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY3YTFjOGQ5NmEwMDI4MzhlOGU0OTUiLCJpYXQiOjE2NTE2Mzk5MTUsImV4cCI6MTY1MTcyNjMxNX0.ujZXAv0-PnSurPoN4hNzbzlLzDZp66ErN4zk21n0gfQ

{
  "name":"K3",
  "address": "Là mã nơi người dân tộc thiểu số và người thuộc hộ gia đình nghèo tham gia BHYT, đang sinh sống tại vùng có điều kiện kinh tế - xã hội đặc biệt khó khăn theo quy định của pháp luật."
}

###
// update
PATCH http://localhost:8080/mfs/edit
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY3YTFjOGQ5NmEwMDI4MzhlOGU0OTUiLCJpYXQiOjE2NTE2Mzk5MTUsImV4cCI6MTY1MTcyNjMxNX0.ujZXAv0-PnSurPoN4hNzbzlLzDZp66ErN4zk21n0gfQ

{
  "_id":"627208338e83ebfc347a9734",
  "name":"K3",
  "address": "Là mã nơi người dân tộc thiểu số và người thuộc hộ gia đình nghèo tham gia BHYT, đang sinh sống tại vùng có điều kiện kinh tế - xã hội đặc biệt khó khăn theo quy định của pháp luật."
}

###
// delete
DELETE  http://localhost:8080/mfs/delete?_id=626f9cd6cf3cfd0bdc68b780
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY3YTFjOGQ5NmEwMDI4MzhlOGU0OTUiLCJpYXQiOjE2NTE2Mzk5MTUsImV4cCI6MTY1MTcyNjMxNX0.ujZXAv0-PnSurPoN4hNzbzlLzDZp66ErN4zk21n0gfQ

###
// get all
GET  http://localhost:8080/mfs/getall
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY3YTFjOGQ5NmEwMDI4MzhlOGU0OTUiLCJpYXQiOjE2NTE2Mzk5MTUsImV4cCI6MTY1MTcyNjMxNX0.ujZXAv0-PnSurPoN4hNzbzlLzDZp66ErN4zk21n0gfQ

###
// get by _id
GET  http://localhost:8080/mfs/getbyid?_id=627208338e83ebfc347a9734
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY3YTFjOGQ5NmEwMDI4MzhlOGU0OTUiLCJpYXQiOjE2NTE2Mzk5MTUsImV4cCI6MTY1MTcyNjMxNX0.ujZXAv0-PnSurPoN4hNzbzlLzDZp66ErN4zk21n0gfQ

###
// search
GET http://localhost:8080/mfs/search?text=k
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY3YTFjOGQ5NmEwMDI4MzhlOGU0OTUiLCJpYXQiOjE2NTE2Mzk5MTUsImV4cCI6MTY1MTcyNjMxNX0.ujZXAv0-PnSurPoN4hNzbzlLzDZp66ErN4zk21n0gfQ